Add template annotations
reactphp/promise pull request #188
Opened 2021-03-15 10:59 UTC by simPod

I was considering adapting this lib for promises though it's currently impossible to be type-safe with it. 

I found this psalm plugin https://github.com/Bocmah/psalm-reactphp-promise-plugin that only includes stubs for psalm. So I was thinking it can be simply ported into this promise lib so it's also supported by phpstan and by any static analysis overall without need for any additional setup.

2021-04-05 10:53 UTC, clue reviewed
@simPod Thanks for bringing this up!

I think this feature makes perfect sense, but I'd like to make sure this is complete before merging this.

In particular, can you add some automated tests to verify this works as expected?

On top of this, phpstan also supports generics, does it make sense to address this as part of the PR?

2021-04-05 11:02 UTC, simPod commented
@clue thanks for input. I'll look into how to test this.

Also note this is only partial implementation (for happy path) as both psalm and phpstan do not support default template types yet (it's impossible to resolve template to a type when `null` is passed).

This is resolving `onFulfilled`'s type but not `onRejected`'s one. I thought it might be a good start anyway to support at least one side for now. Or we keep it here and build up as the support emerges.

Crosslinks:  
https://github.com/vimeo/psalm/issues/5407  
https://github.com/phpstan/phpstan/issues/4801 

> On top of this, phpstan also supports generics, does it make sense to address this as part of the PR?

phpstan reads `@psalm-` annotations so this should be addressed if you meant this.  
(personally, I don't use prefixes at all in my code but as I ported the initial implementation from psalm plugin, I kept them)

2022-01-04 14:47 UTC, Seldaek commented on src/PromiseInterface.php
> +     * @param callable(mixed):TResolve|null $onFulfilled
I'd think this should be `TResolved`, but it's not defined on this method so I don't think that would work? Not sure what this is supposed to do here.

2022-01-04 15:50 UTC, simPod commented
I'll wait for default promise value support in SA since it's fairly useless without it

2022-02-07 10:44 UTC, SimonFrings commented
@simPod thanks for your work on this so far :+1: 

To keep you updated:
@WyriHaximus, @clue and I are currently looking into this, we'll have a call later this day to discuss the details. There's also a discussion in pslam with more information on this: [#7559](https://github.com/vimeo/psalm/discussions/7559).

2022-02-07 11:18 UTC, simPod commented
Thank you for update and pushing it forward!

2022-02-07 12:30 UTC, WyriHaximus commented
One major thing for me was to tackle the bigger picture, so not just this promise package. But also `async` and `await` and observables plus await with observables and get it right as a whole.

2022-03-25 11:46 UTC, WyriHaximus commented
@simPod Just a heads up: I'm going to make a bunch of suggested changes based on https://psalm.dev/r/22a9692a97 thank you for your work so far on this and pushing it forward :+1:

2022-03-27 19:56 UTC, WyriHaximus requested changes
When making the suggestions, I realized I forgot about the other methods, will update https://github.com/vimeo/psalm/discussions/7559 and this PR's suggestions soon

2022-03-27 19:56 UTC, WyriHaximus commented on src/PromiseInterface.php
> +/** @psalm-template T */
```suggestion
/** @template T */
```

2022-03-27 19:56 UTC, WyriHaximus commented on src/PromiseInterface.php
> +     * @return PromiseInterface<TResolved>
```suggestion
     * @template TReturn of mixed
     * 
     * @param callable(T): TReturn $callable
     * 
     * @return (TReturn is PromiseInterface ? TReturn : PromiseInterface<TReturn>)
```

2022-03-27 19:56 UTC, WyriHaximus commented on src/PromisorInterface.php
> +/** @psalm-template T */
```suggestion
/** @template T */
```

2022-05-19 15:07 UTC, WyriHaximus commented
FYI just put up #223 as a draft for the 2.x branch so I can pull it in through composer and test it out again in a project without having to manually edit files again. Will try to get back shortly and hope live doesn't get in between again

2022-06-14 08:04 UTC, spawnia commented on src/PromiseInterface.php
> + * @psalm-template R
Any reason this can not just use `@template`?

2022-06-21 21:55 UTC, WyriHaximus commented
FYI just filed https://github.com/reactphp/promise/pull/227 and https://github.com/reactphp/promise/pull/228 those will not have any direct affect on this PR as it's for the upcoming v3 release. We want basic support out there and then work on getting near to a 100% support out there through this PR and PR's for 1.x and 2.x.

2023-06-22 22:00 UTC, WyriHaximus commented
@simPod Hey if you don't mind I'm going to use your commit as a base to get template annotations + some additional type insurance in.

2023-06-23 06:07 UTC, simPod commented
Awesome 👌🏿

On Fri, Jun 23, 2023, 01:00 Cees-Jan Kiewiet ***@***.***>
wrote:

> @simPod <https://github.com/simPod> Hey if you don't mind I'm going to
> use your commit as a base to get template annotations + some additional
> type insurance in.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reactphp/promise/pull/188#issuecomment-1603368759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQAJLSS6A4Q46K5ZQJXKLXMS57TANCNFSM4ZGKGHSA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-28 14:50 UTC, WyriHaximus commented
PR is up at: https://github.com/reactphp/promise/pull/247

2023-06-29 07:50 UTC, closed without merging