Fix race() to return a forever pending promise when called with an empty array
reactphp/promise pull request #83
Opened 2017-01-11 08:21 UTC by jsor

Fix `race()` to return a forever pending promise when called with an empty array.

Alternative for #81.
See #57 for the discussion.

Closes #57

2017-01-11 20:57 UTC, WyriHaximus approved these changes

2017-01-13 15:26 UTC, jsor commented
Since this PR is approved by @WyriHaximus and @clue is undecided, i'm going to merge this one in the next days (and close #81) if there no any objections.

2017-01-13 18:09 UTC, clue requested changes
I'll keep my vote at +/-0, but I'm tempted to prefer this one because it ensures consistency with ES6 promises.

The changed behavior should be documented in the README (à la bluebird docs), otherwise LGTM :+1:

2017-01-13 19:45 UTC, jsor commented
@clue Good point, note added. 👍

2017-01-14 11:59 UTC, clue approved these changes

2017-01-14 12:24 UTC, merged